"""
Builds data/bot_settings.json from reference/GC Bot Settings.ods -- the weights and thresholds the
strategy bots (engine/bots/strategy_bot.py) play by. Run after editing the spreadsheet:

    python tools/build_bot_settings.py

Sheets read: "Unit Preferences" (per-faction purchase odds), "Strategy Preferences" (per-faction odds of each
strategy style), "Thresholds" (per-style min/max success probabilities, and weights for the secondary
objectives), "Distance" (cost of a square by kind).
"""
import json
import os
import zipfile
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'reference', 'GC Bot Settings.ods')
DST = os.path.join(ROOT, 'data', 'bot_settings.json')

NS = {
    'office': 'urn:oasis:names:tc:opendocument:xmlns:office:1.0',
    'table': 'urn:oasis:names:tc:opendocument:xmlns:table:1.0',
    'text': 'urn:oasis:names:tc:opendocument:xmlns:text:1.0',
}
T = '{%s}' % NS['table']
O = '{%s}' % NS['office']

UNIT_COLUMNS = {
    'Infantry': 'Infantry', 'Mech Inf.': 'Mechanized Infantry', 'Armor': 'Armor',
    'Aircraft Carrier': 'Aircraft Carrier', 'Cruiser': 'Cruiser', 'Submarine': 'Submarine',
    'Bomber': 'Bomber', 'Figher': 'Fighter', 'Fighter': 'Fighter',
}


def read_sheets(path):
    with zipfile.ZipFile(path) as z:
        root = ET.fromstring(z.read('content.xml'))
    sheets = {}
    for table in root.iter(T + 'table'):
        rows = []
        for row in table.iter(T + 'table-row'):
            cells = []
            for cell in row.findall(T + 'table-cell') + []:
                repeat = int(cell.get(T + 'number-columns-repeated', '1'))
                value = cell.get(O + 'value')
                if value is not None:
                    v = float(value)
                    v = int(v) if v == int(v) else v
                else:
                    v = ''.join(''.join(p.itertext()) for p in cell.findall('text:p', NS)).strip()
                cells.extend([v] * min(repeat, 40))
            rows.append(cells)
        sheets[table.get(T + 'name')] = rows
    return sheets


def main():
    sheets = read_sheets(SRC)

    unit_rows = sheets['Unit Preferences']
    header = next(r for r in unit_rows if r and r[1:2] == ['Infantry'])
    unit_weights = {}
    for r in unit_rows:
        if r and isinstance(r[0], str) and r[0] in ('NAA', 'AAC', 'UE', 'GPC', 'PAF', 'UER'):
            unit_weights[r[0]] = {UNIT_COLUMNS[header[i]]: r[i] for i in range(1, len(header)) if header[i] in UNIT_COLUMNS}

    pref_rows = sheets['Strategy Preferences']
    styles = next(r for r in pref_rows if r and r[1:2] == ['Strategic'])[1:6]
    strategy_weights = {}
    for r in pref_rows:
        if r and isinstance(r[0], str) and r[0] in unit_weights:
            strategy_weights[r[0]] = {styles[i]: r[i + 1] for i in range(len(styles))}

    # Thresholds: after a header row, one row per style. Columns (from the sheet):
    # Hold SC (min,max) | Capture SC (min,max) | Reinforce (min,max) | Punish (min,max) |
    # Expand (weight,min,max) | Frontier (w,min,max) | Oceans (w,min,max) | Pursue SC (w,min,max) | 2nd | 3rd
    shape = [('hold_sc', 2), ('capture_sc', 2), ('reinforce_contested', 2), ('punish_betrayers', 2),
             ('expand_territory', 3), ('hold_frontier', 3), ('control_oceans', 3),
             ('pursue_sc_1', 3), ('pursue_sc_2', 3), ('pursue_sc_3', 3)]
    thresholds = {}
    for r in sheets['Thresholds']:
        if r and isinstance(r[0], str) and r[0].strip() in ('Strategic', 'Defensive', 'Expansive', 'Controlling'):
            vals = r[1:]
            entry, i = {}, 0
            for name, width in shape:
                chunk = vals[i:i + width]
                i += width
                entry[name] = ({'min': chunk[0], 'max': chunk[1]} if width == 2
                               else {'weight': chunk[0], 'min': chunk[1], 'max': chunk[2]})
            thresholds[r[0].strip()] = entry

    distance = {}
    for r in sheets['Distance']:
        if r and isinstance(r[0], str) and r[0] in ('Friendly', 'Sea', 'Enemy', 'Allied'):
            distance[r[0].lower()] = r[1]

    out = {
        'note': 'Generated by tools/build_bot_settings.py from reference/GC Bot Settings.ods -- edit the spreadsheet, not this file. '
                'Weights are odds for weighted random draws; min/max are success probabilities in percent.',
        'unit_weights': unit_weights,
        'strategy_weights': strategy_weights,
        'thresholds': thresholds,
        'distance_costs': distance,
    }
    with open(DST, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=2)
        f.write('\n')
    print('wrote', DST)


if __name__ == '__main__':
    main()
