"""
How each module type is laid out as a spreadsheet (sheets/<ModuleType>.ods, one workbook
per module type, every instance of that type in it), and the conversions both ways --
used by tools/export_sheets.py and tools/import_sheets.py (docs/DATA_MODEL.md).

Every workbook has a "Modules" sheet: one row per module instance (its id, name and every
single-valued field -- nested ones as dotted names like generation.budget). Each list in a
module is a sheet of its own, one row per item, its first column the module id; a list
inside a list item (a unit type's abilities, a location's units) is a sheet whose rows also
name that item. Row order is list order.

Columns marked "(info)" are for reading only -- a location's name next to its id, generated
data like adjacency -- and are ignored on import. Fields the sheets don't carry (a location's
boundary polygons, adjacency, label metrics: generated by the map tools) are kept from the
module as it stands.
"""
import copy
import json

INFO = ' (info)'


class Col:
    """One column: `header`, the item field `path` (a key, an int index for list items, or '.'
    for a list of bare values),
    `kind` ('str', 'int', 'num', 'bool', 'json', 'ids'), and whether it is `info` only.
    omit: on import, leave the field out when the cell is empty or holds `default` (the value an
    absent field means)."""

    def __init__(self, header, path=None, kind='str', info=False, omit=False, show=None, default=None):
        self.header = header + (INFO if info else '')
        self.path = header if path is None else path
        self.kind, self.info, self.omit, self.default = kind, info, omit, default
        self.show = show  # info columns: a function (item, doc, ctx) -> value


class Table:
    """A list in the module as a sheet. list_path: a dotted path to the list, or {tag: path}
    with `tag` a column naming which list a row belongs to. key: the item field matching rows to
    existing items (so fields the sheet lacks are kept). parent: (list path, key field, header,
    child field) for a list inside the items of another list. matrix: (child field, column key
    field, value field) -- one column per column key."""

    def __init__(self, sheet, list_path, cols, key=None, parent=None, tag=None, matrix=None):
        self.sheet, self.list_path, self.cols, self.key = sheet, list_path, cols, key
        self.parent, self.tag, self.matrix = parent, tag, matrix


def _loc_name(ctx, tid):
    return ctx['names'].get(tid)


LAYOUTS = {
    'Scenario': [],
    'Map': [
        Table('Locations', 'locations', [
            Col('id', kind='int'), Col('name'), Col('type'), Col('x', kind='num'), Col('y', kind='num'),
            Col('naval_deploy_excluded', kind='bool', omit=True, default=False),
            Col('adjacency', kind='ids', info=True, show=lambda i, d, c: ', '.join(map(str, i.get('adjacency', [])))),
            Col('area_px', info=True, show=lambda i, d, c: i.get('area_px')),
        ], key='id'),
        Table('Adjacency Overrides', {'add': 'adjacency_overrides.add', 'remove': 'adjacency_overrides.remove'}, [
            Col('location_a', 0, 'int'), Col('location_b', 1, 'int'), Col('names', 2),
        ], tag='kind'),
    ],
    'AbilityCatalog': [
        Table('Abilities', 'abilities', [
            Col('id'), Col('name'), Col('description'), Col('listed', kind='bool', omit=True, default=True),
            Col('params', kind='json'), Col('_note', omit=True),
        ]),
    ],
    'UnitSet': [
        Table('Unit Types', 'unit_types', [
            Col('id'), Col('name'), Col('category'), Col('cost', kind='int'), Col('sc_cost', kind='int'),
            Col('attack_die'), Col('damage', kind='int'), Col('defense', kind='int'), Col('hp', kind='int'),
            Col('combat_move', kind='int'), Col('non_combat_move', kind='int'), Col('purchasable', kind='bool'),
            Col('land_order', kind='int'), Col('sea_order', kind='int'), Col('display_order', kind='int'),
            Col('icon'), Col('plural'),
        ], key='id'),
        Table('Unit Abilities', 'abilities', [Col('ability_id', 'id'), Col('params', kind='json', omit=True)],
              parent=('unit_types', 'id', 'unit_type_id', 'abilities')),
    ],
    'MapValues': [
        Table('Values', 'locations', [
            Col('location_id', kind='int'),
            Col('location', info=True, show=lambda i, d, c: _loc_name(c, i['location_id'])),
            Col('value', kind='int'),
        ]),
    ],
    'FactionSet': [
        Table('Factions', 'factions', [Col('id'), Col('name'), Col('color'), Col('icon')]),
    ],
    'FactionAssignment': [
        Table('Locations', 'locations', [
            Col('location_id', kind='int'),
            Col('location', info=True, show=lambda i, d, c: _loc_name(c, i['location_id'])),
            Col('faction_id'), Col('sea_deployment_location_id', kind='int'),
            Col('sea_zone', info=True, show=lambda i, d, c: _loc_name(c, i.get('sea_deployment_location_id'))),
        ]),
    ],
    'SCAssignment': [
        Table('Strategic Centers', 'locations', [
            Col('location_id', '.', 'int'),
            Col('location', info=True, show=lambda i, d, c: _loc_name(c, i)),
        ]),
    ],
    'InitialSetup': [
        Table('Units', 'units', [
            Col('location', info=True, show=lambda i, d, c: None),  # filled per row below
            Col('id'), Col('unit_type_id'), Col('faction_id'), Col('purchased_at', kind='int', omit=True),
        ], parent=('locations', 'location_id', 'location_id', 'units')),
    ],
    'UnitPromotions': [
        Table('Promotions', 'units', [Col('unit_id'), Col('num_promotions', kind='int')]),
    ],
    'RuleSet': [],   # the rules themselves: see TREE below
    'Objectives': [
        Table('Objectives', 'objectives', [Col('id'), Col('name'), Col('kind')]),
    ],
    'PrimaryObjectiveOrder': [
        Table('Steps', {'primary': 'steps', 'final': 'final'}, [
            Col('objective_id'), Col('budget_share', kind='num'), Col('when', omit=True),
        ], tag='list'),
    ],
    'StrategyThresholdSet': [
        Table('Strategies', 'strategies', [Col('id'), Col('name'), Col('variable', kind='bool', omit=True, default=False)], key='id'),
        Table('Thresholds', 'objectives', [
            Col('objective_id'), Col('min_risk', kind='num'), Col('max_risk', kind='num'), Col('weight', kind='num'),
        ], parent=('strategies', 'id', 'strategy_id', 'objectives')),
    ],
    'FactionWeightSet': [
        Table('Factions', 'factions', [Col('faction_id')], key='faction_id'),
        Table('Unit Weights', 'unit_weights', [], parent=('factions', 'faction_id', 'faction_id', 'unit_weights'),
              matrix=('unit_type_id', 'weight')),
        Table('Strategy Weights', 'strategy_weights', [], parent=('factions', 'faction_id', 'faction_id', 'strategy_weights'),
              matrix=('strategy_id', 'weight')),
    ],
}

# Module types whose whole content (bar id/name) is one "path -> value" sheet: the rules are
# mostly prose in a deep tree, so each leaf is a row.
TREE = {'RuleSet': 'Rules'}


# ---- paths --------------------------------------------------------------------------------------

def _get(doc, path, default=None):
    cur = doc
    for part in path.split('.'):
        if not isinstance(cur, dict) or part not in cur:
            return default
        cur = cur[part]
    return cur


def _set(doc, path, value):
    parts = path.split('.')
    cur = doc
    for part in parts[:-1]:
        cur = cur.setdefault(part, {})
    cur[parts[-1]] = value


def _table_paths(module_type):
    out = set()
    for t in LAYOUTS[module_type]:
        if t.parent:
            out.add(t.parent[0])
        elif isinstance(t.list_path, dict):
            out.update(t.list_path.values())
        else:
            out.add(t.list_path)
    return out


def _flatten(doc, claimed, prefix=''):
    """[(dotted path, value)] for every single-valued field outside the claimed list paths."""
    out = []
    for k, v in doc.items():
        path = prefix + k
        if not prefix and k in ('module_type',):
            continue
        if path in claimed:
            continue
        if isinstance(v, dict) and v:
            out.extend(_flatten(v, claimed, path + '.'))
        else:
            out.append((path, v))
    return out


# ---- cells --------------------------------------------------------------------------------------

def to_cell(value, kind):
    if value is None:
        return None
    if kind == 'json' or isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return value


def from_cell(value, kind, where):
    if value is None:
        return None
    if kind == 'int':
        if isinstance(value, bool) or not isinstance(value, (int, float)) or value != int(value):
            if isinstance(value, str) and value.strip().lstrip('-').isdigit():
                return int(value)
            raise ValueError(f'{where}: {value!r} should be a whole number')
        return int(value)
    if kind == 'num':
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            try:
                return float(value) if '.' in str(value) else int(value)
            except ValueError:
                raise ValueError(f'{where}: {value!r} should be a number')
        return value
    if kind == 'bool':
        if isinstance(value, bool):
            return value
        if str(value).strip().lower() in ('true', 'yes', '1', 'x'):
            return True
        if str(value).strip().lower() in ('false', 'no', '0', ''):
            return False
        raise ValueError(f'{where}: {value!r} should be TRUE or FALSE')
    if kind == 'json':
        try:
            return json.loads(value) if isinstance(value, str) else value
        except json.JSONDecodeError as e:
            raise ValueError(f'{where}: not valid JSON ({e})')
    if kind == 'str':
        return value if isinstance(value, str) else (str(int(value)) if isinstance(value, float) and value == int(value)
                                                    else str(value))
    return value


def _scalar_from_cell(value):
    """A Modules-sheet cell: text that is JSON for a list/object is decoded, anything else kept."""
    if isinstance(value, str) and value[:1] in '[{':
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return value
    return value


# ---- export -------------------------------------------------------------------------------------

def export_workbook(module_type, docs, ctx):
    """{sheet: rows} for every doc of `module_type`."""
    sheets = {}
    claimed = _table_paths(module_type)
    if module_type in TREE:
        claimed = {k for d in docs for k in d if k not in ('id', 'name', '_note', '_comment', '_moved')}
    # Modules sheet: the union of every doc's single-valued fields, in first-seen order.
    fields = []
    per_doc = []
    for d in docs:
        flat = dict(_flatten(d, claimed))
        per_doc.append(flat)
        for k in flat:
            if k not in fields:
                fields.append(k)
    sheets['Modules'] = [fields] + [[to_cell(flat.get(k), 'auto') for k in fields] for flat in per_doc]

    for t in LAYOUTS[module_type]:
        rows = []
        if t.matrix:
            col_key, value_key = t.matrix
            keys = []
            for d in docs:
                for p in _get(d, t.parent[0], []):
                    for c in p.get(t.parent[3], []):
                        if c[col_key] not in keys:
                            keys.append(c[col_key])
            rows.append(['module_id', t.parent[2]] + keys)
            for d in docs:
                for p in _get(d, t.parent[0], []):
                    vals = {c[col_key]: c[value_key] for c in p.get(t.parent[3], [])}
                    rows.append([d['id'], p[t.parent[1]]] + [vals.get(k) for k in keys])
        elif t.parent:
            rows.append(['module_id', t.parent[2]] + [c.header for c in t.cols])
            for d in docs:
                for p in _get(d, t.parent[0], []):
                    for item in p.get(t.parent[3], []):
                        row = [d['id'], p[t.parent[1]]]
                        for c in t.cols:
                            if c.info and c.header.startswith('location'):
                                row.append(ctx['names'].get(p[t.parent[1]]))
                            elif c.info:
                                row.append(to_cell(c.show(item, d, ctx), c.kind))
                            else:
                                row.append(to_cell(item.get(c.path), c.kind))
                        rows.append(row)
        else:
            lead = ['module_id'] + ([t.tag] if t.tag else [])
            rows.append(lead + [c.header for c in t.cols])
            for d in docs:
                lists = t.list_path.items() if t.tag else [(None, t.list_path)]
                for tag, path in lists:
                    for item in _get(d, path, []) or []:
                        row = [d['id']] + ([tag] if t.tag else [])
                        for c in t.cols:
                            if c.info:
                                row.append(to_cell(c.show(item, d, ctx), c.kind))
                            elif c.path == '.':
                                row.append(to_cell(item, c.kind))
                            elif isinstance(c.path, int):
                                row.append(to_cell(item[c.path] if c.path < len(item) else None, c.kind))
                            else:
                                row.append(to_cell(item.get(c.path), c.kind))
                        rows.append(row)
        sheets[t.sheet] = rows

    if module_type in TREE:
        rows = [['module_id', 'path', 'value']]
        for d in docs:
            for path, value in _flatten({k: v for k, v in d.items() if k in claimed}, set()):
                rows.append([d['id'], path, to_cell(value, 'auto')])
        sheets[TREE[module_type]] = rows
    return sheets


# ---- import -------------------------------------------------------------------------------------

def _rows(sheets, name):
    rows = sheets.get(name)
    if rows is None:
        raise ValueError(f'the workbook has no {name!r} sheet')
    if not rows:
        return [], []
    header = [str(h) if h is not None else '' for h in rows[0]]
    return header, [r + [None] * (len(header) - len(r)) for r in rows[1:] if any(v is not None for v in r)]


def import_workbook(module_type, sheets, existing):
    """{module id: doc} built from the workbook; `existing` ({id: doc}) supplies the fields the sheets
    don't carry. Raises ValueError naming the sheet and row of a bad cell."""
    header, rows = _rows(sheets, 'Modules')
    if 'id' not in header:
        raise ValueError("the Modules sheet has no 'id' column")
    docs = {}
    claimed = _table_paths(module_type)
    for n, row in enumerate(rows, 2):
        mid = row[header.index('id')]
        if not mid:
            raise ValueError(f'Modules row {n}: no id')
        if mid in docs:
            raise ValueError(f'Modules row {n}: id {mid!r} appears twice')
        doc = copy.deepcopy(existing.get(mid)) or {}
        base = {'module_type': module_type}
        for k, v in doc.items():  # keep what the sheets don't carry, in its place
            base[k] = v
        doc = base
        for h, v in zip(header, row):
            if not h or h.endswith(INFO):
                continue
            _set(doc, h, _scalar_from_cell(v))
        docs[mid] = doc

    for t in LAYOUTS[module_type]:
        header, rows = _rows(sheets, t.sheet)
        col = {h: i for i, h in enumerate(header)}

        def cell(row, h):
            return row[col[h]] if h in col else None

        if t.parent:
            plist, pkey, pheader, child = t.parent
            fresh = {mid: {} for mid in docs}  # module -> parent key -> new child list
            for n, row in enumerate(rows, 2):
                mid = cell(row, 'module_id')
                if mid not in docs:
                    raise ValueError(f'{t.sheet} row {n}: unknown module id {mid!r}')
                key = row[col[pheader]]
                if isinstance(key, float) and key == int(key):
                    key = int(key)
                items = fresh[mid].setdefault(key, [])
                if t.matrix:
                    col_key, value_key = t.matrix
                    for h in header[2:]:
                        v = cell(row, h)
                        if v is not None:
                            items.append({col_key: h, value_key: from_cell(v, 'num', f'{t.sheet} row {n}')})
                else:
                    items.append(_item_from_row(t, row, col, f'{t.sheet} row {n}'))
            for mid, doc in docs.items():
                parents = _get(doc, plist)
                if parents is None:
                    parents = []
                    _set(doc, plist, parents)
                by_key = {p.get(pkey): p for p in parents}
                for key, items in fresh[mid].items():
                    if key not in by_key:
                        p = {pkey: key}
                        parents.append(p)
                        by_key[key] = p
                    by_key[key][child] = items
                for p in parents:
                    if p.get(pkey) not in fresh[mid] and child in p:
                        p[child] = []
                if t.key is None and t.parent[0] == plist and not any(tt.list_path == plist for tt in LAYOUTS[module_type]):
                    # a list only this sheet defines (a setup's locations): drop parents with no rows
                    parents[:] = [p for p in parents if p.get(child)]
            continue

        lists = t.list_path.items() if t.tag else [(None, t.list_path)]
        fresh = {mid: {tag: [] for tag, _ in lists} for mid in docs}
        for n, row in enumerate(rows, 2):
            mid = cell(row, 'module_id')
            if mid not in docs:
                raise ValueError(f'{t.sheet} row {n}: unknown module id {mid!r}')
            tag = cell(row, t.tag) if t.tag else None
            if tag not in fresh[mid]:
                raise ValueError(f'{t.sheet} row {n}: {t.tag} must be one of {sorted(fresh[mid])}')
            fresh[mid][tag].append(_item_from_row(t, row, col, f'{t.sheet} row {n}'))
        for mid, doc in docs.items():
            for tag, path in lists:
                items = fresh[mid][tag]
                if t.key:
                    old = {i.get(t.key): i for i in (_get(doc, path) or []) if isinstance(i, dict)}
                    merged = []
                    for item in items:
                        m = copy.deepcopy(old.get(item.get(t.key), {}))
                        for c in t.cols:
                            if c.info or c.path == '.' or isinstance(c.path, int):
                                continue
                            if c.path in item:
                                m[c.path] = item[c.path]
                            else:
                                m.pop(c.path, None)
                        ordered = {c.path: m[c.path] for c in t.cols if not c.info and c.path in m}
                        ordered.update({k: v for k, v in m.items() if k not in ordered})
                        merged.append(_reorder_like(ordered, old.get(item.get(t.key))))
                    items = merged
                _set(doc, path, items)

    if module_type in TREE:
        header, rows = _rows(sheets, TREE[module_type])
        col = {h: i for i, h in enumerate(header)}
        fresh = {mid: {} for mid in docs}
        for n, row in enumerate(rows, 2):
            mid = row[col['module_id']]
            if mid not in docs:
                raise ValueError(f'{TREE[module_type]} row {n}: unknown module id {mid!r}')
            _set(fresh[mid], row[col['path']], _scalar_from_cell(row[col['value']]))
        for mid, doc in docs.items():
            keep = {k: v for k, v in doc.items() if k in ('module_type', 'id', 'name', '_note', '_comment', '_moved')}
            order = list(doc)
            doc.clear()
            doc.update(keep)
            doc.update(fresh[mid])
            ranked = {k: i for i, k in enumerate(order)}
            items = sorted(doc.items(), key=lambda kv: ranked.get(kv[0], len(ranked)))
            doc.clear()
            doc.update(items)
    return docs


def _reorder_like(item, old):
    """`item` with its keys in `old`'s order (new keys last), so an unchanged item stays byte-identical."""
    if not old:
        return item
    ranked = {k: i for i, k in enumerate(old)}
    return dict(sorted(item.items(), key=lambda kv: ranked.get(kv[0], len(ranked))))


def _item_from_row(t, row, col, where):
    fields = [c for c in t.cols if not c.info]
    if any(isinstance(c.path, int) for c in fields):  # a list item: [a, b, note]
        return [from_cell(row[col[c.header]], c.kind, f'{where}, {c.header}') for c in fields]
    if len(fields) == 1 and fields[0].path == '.':  # a bare value
        c = fields[0]
        return from_cell(row[col[c.header]], c.kind, f'{where}, {c.header}')
    item = {}
    for c in fields:
        v = from_cell(row[col[c.header]] if c.header in col else None, c.kind, f'{where}, {c.header}')
        if c.omit and (v is None or v == {} or v == '' or (c.default is not None and v == c.default)):
            continue
        item[c.path] = v
    return item
